Feat/5 implement home page dark version
codealoy/codealoy pull request #15
Opened 2022-10-26 05:03 UTC by alaminsahed

* Home page dark version
* Change the background and text for the dark version

2022-10-27 13:16 UTC, mimukit requested changes
Change required:

1. "Call to action" section doesn't need any change. Keep it the same as the light version.

![CleanShot 2022-10-27 at 19 11 03@2x](https://user-images.githubusercontent.com/11677026/198294653-8e949c6a-4df5-435f-98b8-012bf315e065.png)

2022-10-27 17:04 UTC, alaminsahed commented
change the action section as light mode.

2022-10-28 04:10 UTC, mimukit commented on src/components/home/CTA.tsx
> +    <div className=" bg-indigo-700   ">
Unnecessary whitespace before and after the class name.

2022-10-28 04:16 UTC, mimukit approved these changes

2022-10-28 04:16 UTC, mimukit approved these changes

2022-10-28 04:24 UTC, merged