feat: :sparkles: create top progress with gradient color
codealoy/codealoy pull request #50
Opened 2022-12-22 17:58 UTC by sakilk130

top progress bar with gradient color

2023-01-22 16:04 UTC, mimukit requested changes
Great work @sakilk130. A couple of small changes are requested.

2023-01-22 16:04 UTC, mimukit commented on src/pages/_app.tsx
> +import 'nprogress/nprogress.css';
Move this CSS file import to the CSS import block below:

```diff
import 'focus-visible';
- import 'nprogress/nprogress.css';
import Head from 'next/head';
import superjson from 'superjson';
import { Baloo_Da_2 } from '@next/font/google';

+ import 'nprogress/nprogress.css';
import '../styles/globals.css';
import '../styles/tailwind.css';
```

2023-01-22 16:04 UTC, mimukit commented on src/pages/_app.tsx
> +import ProgressBar from '../components/ProgressBar';
Update the import to the named import:

```diff
- import ProgressBar from '../components/ProgressBar';
+ import { ProgressBar } from '../components/ProgressBar';
```

2023-02-12 16:05 UTC, sakilk130 commented
Thank you @mimukit Bhai for your review.
I already fix those little changes. Please have a look.

2023-02-12 18:32 UTC, mimukit approved these changes

2023-02-12 18:33 UTC, merged